name: comif_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_login: ^4.1.1
  http: ^1.1.0
  crypto: ^3.0.3
  flutter_launcher_icons: ^0.13.1
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: bonbon
      fonts:
        - asset: assets/FontsFree-Net-bonbon-regular.ttf
      
    - family: HouseScript
      fonts:
        - asset: assets/SignPainter-HouseScript.ttf

  assets:
    - assets/logo_comif.png
    - assets/FontsFree-Net-bonbon-regular.ttf
    - assets/SignPainter-HouseScript.ttf

cupertino_icons: ^0.1.3

flutter_icons:
  android: true
  ios: true
  image_path_ios: "assets/logo_comif.png"  # Path to your iOS app icon
  image_path_android: "assets/logo_comif.png"  # Path to your Android app icon
