name: comif_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_login: ^4.1.1
  http: ^1.1.0
  crypto: ^3.0.3
  flutter_launcher_icons: ^0.13.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: Bonbon
      fonts:
      - asset:  assets/FontsFree-Net-bonbon-regular.ttf
      
    - family: HouseScript
      fonts:
      - asset:  assets/SignPainter-HouseScript.ttf
  assets:
      - assets/logo_comif.png
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo_comif.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logo_comif.png"
    background_color: "#000000"
    theme_color: "#000000"
  windows:
    generate: true
    image_path: "assets/logo_comif.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/logo_comif.png"

